version: '3'

services:
  api:
    container_name: rest-api
    build:
      context: .
      dockerfile: DockerfileApi
    command: uvicorn app.api:app --host 0.0.0.0 --port 5435
    restart: unless-stopped
    expose:
      - 5435
    environment:
      - DATABASE_URL_LOCAL=postgresql://fastapi_user:fastapi_pass@localhost:5432/fastapi_api
      - CONFIG_PASSWORD_EXAMPLE=qaz1xsw2edc3
      - CONFIG_EMAIL_EXAMPLE=emailname@email.ru
    depends_on:
      - redis
    network_mode: host

  db:
    container_name: api-db
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi_user
      - POSTGRES_PASSWORD=fastapi_pass
      - POSTGRES_DB=fastapi_api
    network_mode: host

  worker:
    container_name: worker
    build:
      dockerfile: DockerfileCelery
      context: .
    volumes:
      - ./:/app/
      - celery_data:/data
    network_mode: host
    environment:
      - C_FORCE_ROOT=true
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - CELERY_RESULT_BACKEND=redis://localhost:6379/0
    depends_on:
      - redis
    

  redis:
    container_name: redis
    image: redis
    depends_on:
      - db
    expose:
      - 6379
    network_mode: host


volumes:
  postgres_data:
  celery_data:
  