import os

DATABASE_URL: str = os.getenv('DATABASE_URL_LOCAL')
if not DATABASE_URL:
    from config import CONFIG_DATABASE_URL

    DATABASE_URL = CONFIG_DATABASE_URL


PASSWORD_EXAMPLE: str = os.getenv('CONFIG_PASSWORD_EXAMPLE')
if not PASSWORD_EXAMPLE:
    from config import CONFIG_PASSWORD_EXAMPLE

    PASSWORD_EXAMPLE = CONFIG_PASSWORD_EXAMPLE

EMAIL_EXAMPLE: str = os.getenv('CONFIG_EMAIL_EXAMPLE')
if not EMAIL_EXAMPLE:
    from config import CONFIG_EMAIL_EXAMPLE

    EMAIL_EXAMPLE = CONFIG_EMAIL_EXAMPLE
